### your site title here

title: home
permalink: :title/
sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md

highlighter: rouge
markdown: kramdown

# Tracker
analytics: G-FNB5VFLLXD

# Comments. Now using giscus using the same disqus template :-)
disqus-shortname: 

